### ISSUE TITLE
No notification

### ISSUE THREAD

**Issue by parnekov** [udacity/AdvancedAndroid_Squawker#14]
I have checked Squawker is in the background and connected to the internet and included the FCM library.
But I don't see the notification of the first message.  What could be the problem? Thank you!

**Comment by shashankSkydale** [comment]
> I have checked Squawker is in the background and connected to the internet and included the FCM library.
> But I don't see the notification of the first message. What could be the problem? Thank you!

Hi Parnekov,
I'm also facing the same issue and not sure where exactly is the problem.
If you are aware of the solution please help me.
