### ISSUE TITLE
Unable to run the apk on Phone

### ISSUE THREAD

**Issue by shashankSkydale** [udacity/AdvancedAndroid_Squawker#31]
Getting below error after pressing play button in android studio which is meant to launch apk on smartphone

Cannot specify -processorpath or --processor-path via `CompileOptions.compilerArgs`. Use the `CompileOptions.annotationProcessorPath` property instead.

**Comment by shashankSkydale** [comment]
Please help since I'm unable to run any branch from this repository and stuck at this point.

**Comment by lilianausvat** [comment]
I have the same problem. Can you please update the project?

**Comment by Himato** [comment]
In the app level build.gradle file: Change this line replacing `apt` with `annotationProcessor`:
`apt 'net.simonvt.schematic:schematic-compiler:0.6.3'`

**Comment by lilianausvat** [comment]
how we are suppose to know this ? The problem is that all the projects in Android advanced course are outdated . The course should be updated . All projects that are older that 2 years are not functional projects. So how are we suppose to learn from those projects if we cannot run them?

**Comment by Himato** [comment]
Totally agree.

**Comment by Himato** [comment]
I totally agree.

**Comment by shashankSkydale** [comment]
Hi Himato,
Still the same error I'm getting even after your suggestion.
Its driving me nuts now and unable to proceed and learn.

**Comment by shashankSkydale** [comment]
Even I comment the line below line still the same error occurs

`apt 'net.simonvt.schematic:schematic-compiler:0.6.3'`
> 
> 
> In the app level build.gradle file: Change this line replacing `apt` with `annotationProcessor`:
> `apt 'net.simonvt.schematic:schematic-compiler:0.6.3'`

Not working please help and unable to proceed.

**Comment by Himato** [comment]
It worked for me but try also to remove these lines: -
1. In project level "build.gradle" remove this line:
     `classpath 'com.neenbedankt.gradle.plugins:android-apt:1.2'`
2. In app level "build.gradle" remove this line:
     `apply plugin: 'android-apt'`

**Comment by shashankSkydale** [comment]
> 
> 
> It worked for me but try also to remove these lines: -
> 
>     1. In project level "build.gradle" remove this line:
>        `classpath 'com.neenbedankt.gradle.plugins:android-apt:1.2'`
> 
>     2. In app level "build.gradle" remove this line:
>        `apply plugin: 'android-apt'`

Thanks a ton Himato, Finally the app worked on my smartphone

**Comment by Himato** [comment]
You're welcome!

**Comment by shashankSkydale** [comment]
Hi Himato,
As part of exercise -01 I've set notification in firebase console and followed all instructions but not receiving notification on my smartphone.
Can you assist me what I'm missing here ?

**Comment by shashankSkydale** [comment]
Closing the issue since suggestion provided by Himato are working.
